// firebase-vue/src/components/Todo.vue
<template>
    <li class="mdl-list__item mdl-list__item--two-line">
        <span class="mdl-list__item-primary-content">
            <img v-if="data.image" :src="data.image" class="mdl-list__item-avatar">
            <i v-else class="material-icons mdl-list__item-avatar">person</i>
            
            <span>{{ data.title }}</span>
            <span class="mdl-list__item-sub-title">{{ data.description }}</span>
        </span>
        <span class="mdl-list__item-secondary-content">
            <a class="mdl-list__item-secondary-action" href="#" @click.prevent="$emit('edit-todo')"><i class="material-icons">edit</i></a>
        </span>
        <span class="mdl-list__item-secondary-content">
            <a class="mdl-list__item-secondary-action" href="#" @click.prevent="$emit('delete-todo')"><i class="material-icons">delete</i></a>
        </span>
    </li>
</template>

<script>
export default {
  props: ['data'],
};
</script>

// firebase-angular/src/app/todo/todo.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css'],
})
export class TodoComponent implements OnInit {
  @Input()
  data: Todo;

  @Output()
  edit = new EventEmitter<Todo>();

  @Output()
  delete = new EventEmitter<Todo>();

  constructor() {}

  ngOnInit() {}

  editTodo(event: Event) {
    event.preventDefault();

    this.edit.emit(this.data);
  }

  deleteTodo(event: Event) {
    event.preventDefault();

    this.delete.emit(this.data);
  }
}

<li class="mdl-list__item mdl-list__item--two-line">
  <span class="mdl-list__item-primary-content">
    <img *ngIf="data.image;else icon" [src]="data.image" class="mdl-list__item-avatar">
    <ng-template #icon>
      <i v-else class="material-icons mdl-list__item-avatar">person</i>
    </ng-template>

    <span>{{ data.title }}</span>
    <span class="mdl-list__item-sub-title">{{ data.description }}</span>
  </span>
  <span class="mdl-list__item-secondary-content">
    <a class="mdl-list__item-secondary-action" href="#" (click)="editTodo($event)">
      <i class="material-icons">edit</i>
    </a>
  </span>
  <span class="mdl-list__item-secondary-content">
    <a class="mdl-list__item-secondary-action" href="#" (click)="deleteTodo($event)">
      <i class="material-icons">delete</i>
    </a>
  </span>
</li>
