// firebase-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { AngularFireAuth } from 'angularfire2/auth';

declare const componentHandler;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  isLoggedIn = false;

  constructor(private afAuth: AngularFireAuth, private router: Router) {
    // MDL router change things
    router.events.subscribe(val => {
      if (val instanceof NavigationEnd) {
        if (!(typeof componentHandler === 'undefined')) {
          setTimeout(() => {
            componentHandler.upgradeAllRegistered();
          }, 250);
        }

        const drawer = document.querySelector('.mdl-layout__drawer');

        if (drawer && drawer.classList.contains('is-visible')) {
          document
            .querySelector('.mdl-layout__obfuscator')
            .classList.remove('is-visible');
          drawer.classList.remove('is-visible');
        }
      }
    });

    afAuth.authState.subscribe(user => {
      if (user) {
        this.isLoggedIn = true;
        return;
      }

      this.isLoggedIn = false;
    });
  }

  logout() {
    this.afAuth.auth
      .signOut()
      .then(() => {
        alert('You have been logged out successfully.');
        this.router.navigate(['/']);
      })
      .catch(() => {
        alert('An error occurred.');
      });
  }
}

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
mdl-layout--fixed-header" id="app">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Firebase To-Do</span>
      <div class="mdl-layout-spacer"></div>
      <button class="mdl-button mdl-button--icon" title="Log Out" *ngIf="isLoggedIn" (click)="logout()">
        <i class="material-icons">exit_to_app</i>
      </button>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">To-Do</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" routerLink="/" *ngIf="!isLoggedIn">Login</a>
      <a class="mdl-navigation__link" routerLink="create-account" *ngIf="!isLoggedIn">Create Account</a>
      <a class="mdl-navigation__link" routerLink="todos" *ngIf="isLoggedIn">To-Dos</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content">
      <router-outlet></router-outlet>
    </div>
  </main>
</div>

// firebase-vue/src/App.vue
<template>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
mdl-layout--fixed-header" id="app">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <span class="mdl-layout-title">Firebase To-Do</span>
            <div class="mdl-layout-spacer"></div>
            <button class="mdl-button mdl-button--icon" title="Log Out" v-if="isLoggedIn" @click="logout()">
                <i class="material-icons">exit_to_app</i>
            </button>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">To-Do</span>
        <nav class="mdl-navigation">
            <router-link class="mdl-navigation__link" to="/" v-if="!isLoggedIn">Login</router-link>
            <router-link class="mdl-navigation__link" to="create-account" v-if="!isLoggedIn">Create Account</router-link>
            <router-link class="mdl-navigation__link" to="todos" v-if="isLoggedIn">To-Dos</router-link>
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content">
            <router-view />
        </div>
    </main>
  </div>
</template>

<script>
import firebase from 'firebase';

export default {
  name: 'app',
  mounted() {
    firebase.auth().onAuthStateChanged(user => {
      this.isLoggedIn = !!user;
    });
  },
  data() {
    return {
      isLoggedIn: false,
    };
  },
  methods: {
    logout() {
      firebase.auth().signOut()
        .then(() => {
          alert('You have been logged out successfully.');
          this.$router.push('/');
        })
        .catch(() => {
          alert('An error occurred.');
        });
    }
  }
}
</script>

<style>
body {
  background-color: #eeeeee;
}

.mdl-textfield {
  width: 100%;
}

.mdl-card__actions {
  text-align: right;
}

button.login-with {
  width: 100%;
  margin-bottom: 10px;
}
</style>
